apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: express-js-sample
  name: express-js-sample
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-js-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: express-js-sample
    spec:
      containers:
      - image: docker.io/salamflamo/express-js-sample:latest
        name: express-js-sample
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: express-js-sample
  name: express-js-sample
  namespace: sample
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-js-sample
  type: ClusterIP
status:
  loadBalancer: {}
