apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: express-js-sample
  name: express-js-sample
  namespace: sample
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-js-sample
  type: ClusterIP
status:
  loadBalancer: {}
